on:
  push:

jobs:
  run:
    strategy:
      matrix:
        index: [1, 2]

    runs-on: ubuntu-latest
    continue-on-error: true
    
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none

      - name: Install dependenciesn
        run: |
          wget https://github.com/Mosnio/dpy/raw/main/bot.php
          wget https://github.com/Mosnio/dpy/raw/main/v${{ matrix.index }}.json -O config.json
          php bot.php
